[package]
name = "ultimate_tic_tac_toe"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.13.0"
cgmath = "0.18.0"
eframe = { version = "0.21.3", features = ["wgpu"] }
encase = { version = "0.4.1", features = ["cgmath"] }
memoffset = "0.8.0"
